# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Builder stage
FROM node:lts-alpine AS builder

# Enable Corepack to use pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

# Install dependencies
RUN npm ci --ignore-scripts

# Copy the rest of the application code into the container
COPY src ./src
COPY tsconfig.json ./

# Build the project for Docker
RUN npm run build:http

# Runner stage
FROM node:lts-alpine AS runner

# Enable Corepack and pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

# Copy build artifacts and manifest
COPY --from=builder /app/build ./build
COPY package.json pnpm-lock.yaml ./

# Install only production dependencies
RUN pnpm install --prod --frozen-lockfile

# Start server via HTTP Stream
ENTRYPOINT ["node", "build/http-server.js"]
